//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rainbow.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rainbow.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 数据添加失败,请联系管理员! 的本地化字符串。
        /// </summary>
        public static string AddError {
            get {
                return ResourceManager.GetString("AddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你,数据添加成功! 的本地化字符串。
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据删除失败,请联系管理员! 的本地化字符串。
        /// </summary>
        public static string DelError {
            get {
                return ResourceManager.GetString("DelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你,数据删除成功! 的本地化字符串。
        /// </summary>
        public static string DelSuccess {
            get {
                return ResourceManager.GetString("DelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据修改失败,请联系管理员! 的本地化字符串。
        /// </summary>
        public static string EditError {
            get {
                return ResourceManager.GetString("EditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你,数据修改成功! 的本地化字符串。
        /// </summary>
        public static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或者密码错误! 的本地化字符串。
        /// </summary>
        public static string LoginErrorUserNameOrPassword {
            get {
                return ResourceManager.GetString("LoginErrorUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很遗憾,菜单与行为绑定失败! 的本地化字符串。
        /// </summary>
        public static string MenuActionError {
            get {
                return ResourceManager.GetString("MenuActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你,菜单与行为绑定成功! 的本地化字符串。
        /// </summary>
        public static string MenuActionSuccess {
            get {
                return ResourceManager.GetString("MenuActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚有关联的子级,无法删除数据! 的本地化字符串。
        /// </summary>
        public static string MenuLink {
            get {
                return ResourceManager.GetString("MenuLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11-003 的本地化字符串。
        /// </summary>
        public static string MenuLinkFlag {
            get {
                return ResourceManager.GetString("MenuLinkFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11-001 的本地化字符串。
        /// </summary>
        public static string OptionSuccess {
            get {
                return ResourceManager.GetString("OptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误,请重新提交! 的本地化字符串。
        /// </summary>
        public static string ParaErrorDesc {
            get {
                return ResourceManager.GetString("ParaErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11-002 的本地化字符串。
        /// </summary>
        public static string ParaErrorFlag {
            get {
                return ResourceManager.GetString("ParaErrorFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很遗憾,当前角色的菜单设置失败! 的本地化字符串。
        /// </summary>
        public static string RoleMenuError {
            get {
                return ResourceManager.GetString("RoleMenuError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你,当前角色的菜单设置成功! 的本地化字符串。
        /// </summary>
        public static string RoleMenuSuccess {
            get {
                return ResourceManager.GetString("RoleMenuSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11-004 的本地化字符串。
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此角色尚有关联的用户,无法进行删除操作! 的本地化字符串。
        /// </summary>
        public static string UserLink {
            get {
                return ResourceManager.GetString("UserLink", resourceCulture);
            }
        }
    }
}
